### ISSUE TITLE
Copyright Violation

### ISSUE THREAD

**Issue by CentauriSoldier** [xanathar/grimwidgets#7]
The grimwidgets/Util.lua file was written by me (some items from LuaX, some from my work on Legend of Grimrock). Please correctly attribute me for my work. You may place the code below in the file header for copyright compliance, Thank you. 

To view some of the source, please follow the link below.
https://github.com/CentauriSoldier/luax/blob/master/modules/table.lua

--[[
> Concept and Code By Centauri Soldier
> http://www.github.com/CentauriSoldier
>
> This work is licensed under the Creative Commons Attribution-ShareAlike 3.0 Unported License.
> To view a copy of this license, visit http://creativecommons.org/licenses/by-sa/3.0/
> or send a letter to Creative Commons, 444 Castro Street, Suite 900, Mountain View, California, 94041, USA.
--]]

**Comment by tomaszmrugalski** [comment]
Wow! Grimrock is still alive. I haven't played, much less did anything related to modding in years.

Sorry for not attributing you earlier. Back in the early days code was flowing freely and it was a bit tricky to track who contributed what.

Anyway, just pushed the requested header update. If it's ok, please close the issue. If not, let's discuss what else has to be done.

Note to self: Did I really wrote any of that lua stuff? I don't remember a thing. What's lua, anyway? :)

**Comment by CentauriSoldier** [comment]
It is on my PC :P. I still play it and am also starting a new mod project after this quarter. Thank you very much for correcting the issue. Happy coding :).
